
import { useState } from "react"
import { Link } from "react-router-dom"
import "./notice.css"

const notices = [
    {
        _id: "64ca92788ff1ae63f13b1f6c",
        title: "Its notice title",
        disc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magni facere itaque facilis laboriosam explicabo eligendi? Adipisci incidunt ab explicabo ut dolores dolorum deleniti recusandae, laboriosam iure pariatur possimus, animi libero vero, ea tenetur. Beatae porro labore rerum eligendi ea consequuntur voluptas voluptatem voluptate incidunt nostrum. Autem, quaerat quidem. Consectetur ipsum accusantium, ipsam neque ut expedita totam quisquam adipisci quia! Aliquam et modi soluta ad dolores? Optio doloribus unde eveniet obcaecati veritatis dicta possimus enim amet perspiciatis ratione repellendus reprehenderit, numquam voluptatibus labore, magnam iusto aperiam magni quos laudantium cumque?"
    },
    {
        _id: "64ca92788ff1ae63f13b1f6c",
        title: "Its notice title",
        disc: "Lorem ieimus enim amet perspiciatis ratione repellendus reprehenderit, numquam voluptatibus labore, magnam iusto aperiam magni quos laudantium cumque?"
    },
    {
        _id: "64ca92788ff1ae63f13b1f6c",
        title: "Its notice title",
        disc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magni facere itaque facilis laboriosam explicabo eligendi, praesentium nulla esse quos atque veritatis fugit accusantium debitis cupiditate obcaecati possimus dignissimos incidunt molestiae quis repellat eum eos est. Tempore veritatis ratione atque, consequuntur repellendus cumque similique sequi? Exercitationem aut nulla provident suscipit eaque, ullam qui dolor earum. Error nihil culpa, maxime pariatur nobis ab maiores corrupti explicabo et dicta iste doloribus ipsum iusto ut soluta eum laboriosam provident eos architecto totam tempore incidunt blanditiis dolores! Doloribus, consectetur. Quae repudiandae porro rerum corporis voluptatem, assumenda vitae ad totam quasi voluptatum pariatur dignissimos praesentium soluta dicta provident! Ea provident vero excepturi perspiciatis sunt quidem alias, officiis eveniet. Incidunt voluptate sunt, quasi veritatis eos, facilis nemo consequatur, excepturi voluptas temporibus cupiditate quos magni voluptatum id! Ea quos culpa eveniet! Sequi iure magnam velit, voluptatum molestiae sed, soluta perspiciatis eveniet aliquam repellat nam distinctio corrupti quidem eius eligendi amet harum tempora nesciunt cupiditate culpa odit neque inventore assumenda debitis! Minima voluptatibus autem vel omnis tempora exercitationem ex error dolor sequi, quaerat aliquid nihil sit debitis porro numquam. Quibusdam soluta repellendus nemo ipsam reiciendis quasi consectetur ab. Eius et nesciunt, dolores ullam ad, delectus nihil sapiente iure perspiciatis distinctio quibusdam repudiandae. Atque libero excepturi cumque, fugit cum facilis asperiores cupiditate iusto ratione reiciendis aliquam labore est mollitia velit corrupti perferendis exercitationem. Fugit, amet veritatis? Adipisci incidunt ab explicabo ut dolores dolorum deleniti recusandae, laboriosam iure pariatur possimus, animi libero vero, ea tenetur. Beatae porro labore rerum eligendi ea consequuntur voluptas voluptatem voluptate incidunt nostrum. Autem, quaerat quidem. Consectetur ipsum accusantium, ipsam neque ut expedita totam quisquam adipisci quia! Aliquam et modi soluta ad dolores? Optio doloribus unde eveniet obcaecati veritatis dicta possimus enim amet perspiciatis ratione repellendus reprehenderit, numquam voluptatibus labore, magnam iusto aperiam magni quos laudantium cumque?"
    },
    {
        _id: "64ca92788ff1ae63f13b1f6c",
        title: "Its notice title",
        disc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magni facere itaque facilis laboriosam explicabo eligendi, praesentium nulla esse quos atque veritatis fugit accusantium debitis cupiditate obcaecati possimus dignissimos incidunt molestiae quis repellat eum eos est. Tempore veritatis ratione atque, consequuntur repellendus cumque similique sequi? Exercitationem aut nulla provident suscipit eaque, ullam qui dolor earum. Error nihil culpa, maxime pariatur nobis ab maiores corrupti explicabo et dicta iste doloribus ipsum iusto ut soluta eum laboriosam provident eos architecto totam tempore incidunt blanditiis dolores! Doloribus, consectetur. Quae repudiandae porro rerum corporis voluptatem, assumenda vitae ad totam quasi voluptatum pariatur dignissimos praesentium soluta dicta provident! Ea provident vero excepturi perspiciatis sunt quidem alias, officiis eveniet. Incidunt voluptate sunt, quasi veritatis eos, facilis nemo consequatur, excepturi voluptas temporibus cupiditate quos magni voluptatum id! Ea quos culpa eveniet! Sequi iure magnam velit, voluptatum molestiae sed, soluta perspiciatis eveniet aliquam repellat nam distinctio corrupti quidem eius eligendi amet harum tempora nesciunt cupiditate culpa odit neque inventore assumenda debitis! Minima voluptatibus autem vel omnis tempora exercitationem ex error dolor sequi, quaerat aliquid nihil sit debitis porro numquam. Quibusdam soluta repellendus nemo ipsam reiciendis quasi consectetur ab. Eius et nesciunt, dolores ullam ad, delectus nihil sapiente iure perspiciatis distinctio quibusdam repudiandae. Atque libero excepturi cumque, fugit cum facilis asperiores cupiditate iusto ratione reiciendis aliquam labore est mollitia velit corrupti perferendis exercitationem. Fugit, amet veritatis? Adipisci incidunt ab explicabo ut dolores dolorum deleniti recusandae, laboriosam iure pariatur possimus, animi libero vero, ea tenetur. Beatae porro labore rerum eligendi ea consequuntur voluptas voluptatem voluptate incidunt nostrum. Autem, quaerat quidem. Consectetur ipsum accusantium, ipsam neque ut expedita totam quisquam adipisci quia! Aliquam et modi soluta ad dolores? Optio doloribus unde eveniet obcaecati veritatis dicta possimus enim amet perspiciatis ratione repellendus reprehenderit, numquam voluptatibus labore, magnam iusto aperiam magni quos laudantium cumque?"
    },
    {
        _id: "64ca92788ff1ae63f13b1f6c",
        title: "Its notice title",
        disc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magni facere itaque facilis laboriosam explicabo eligendi, praesentium nulla esse quos atque veritatis fugit accusantium debitis cupiditate obcaecati possimus dignissimos incidunt molestiae quis repellat eum eos est. Tempore veritatis ratione atque, consequuntur repellendus cumque similique sequi? Exercitationem aut nulla provident suscipit eaque, ullam qui dolor earum. Error nihil culpa, maxime pariatur nobis ab maiores corrupti explicabo et dicta iste doloribus ipsum iusto ut soluta eum laboriosam provident eos architecto totam tempore incidunt blanditiis dolores! Doloribus, consectetur. Quae repudiandae porro rerum corporis voluptatem, assumenda vitae ad totam quasi voluptatum pariatur dignissimos praesentium soluta dicta provident! Ea provident vero excepturi perspiciatis sunt quidem alias, officiis eveniet. Incidunt voluptate sunt, quasi veritatis eos, facilis nemo consequatur, excepturi voluptas temporibus cupiditate quos magni voluptatum id! Ea quos culpa eveniet! Sequi iure magnam velit, voluptatum molestiae sed, soluta perspiciatis eveniet aliquam repellat nam distinctio corrupti quidem eius eligendi amet harum tempora nesciunt cupiditate culpa odit neque inventore assumenda debitis! Minima voluptatibus autem vel omnis tempora exercitationem ex error dolor sequi, quaerat aliquid nihil sit debitis porro numquam. Quibusdam soluta repellendus nemo ipsam reiciendis quasi consectetur ab. Eius et nesciunt, dolores ullam ad, delectus nihil sapiente iure perspiciatis distinctio quibusdam repudiandae. Atque libero excepturi cumque, fugit cum facilis asperiores cupiditate iusto ratione reiciendis aliquam labore est mollitia velit corrupti perferendis exercitationem. Fugit, amet veritatis? Adipisci incidunt ab explicabo ut dolores dolorum deleniti recusandae, laboriosam iure pariatur possimus, animi libero vero, ea tenetur. Beatae porro labore rerum eligendi ea consequuntur voluptas voluptatem voluptate incidunt nostrum. Autem, quaerat quidem. Consectetur ipsum accusantium, ipsam neque ut expedita totam quisquam adipisci quia! Aliquam et modi soluta ad dolores? Optio doloribus unde eveniet obcaecati veritatis dicta possimus enim amet perspiciatis ratione repellendus reprehenderit, numquam voluptatibus labore, magnam iusto aperiam magni quos laudantium cumque?"
    },
    {
        _id: "64ca92788ff1ae63f13b1f6c",
        title: "Its notice title",
        disc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magni facere itaque facilis laboriosam explicabo eligendi, praesentium nulla esse quos atque veritatis fugit accusantium debitis cupiditate obcaecati possimus dignissimos incidunt molestiae quis repellat eum eos est. Tempore veritatis ratione atque, consequuntur repellendus cumque similique sequi? Exercitationem aut nulla provident suscipit eaque, ullam qui dolor earum. Error nihil culpa, maxime pariatur nobis ab maiores corrupti explicabo et dicta iste doloribus ipsum iusto ut soluta eum laboriosam provident eos architecto totam tempore incidunt blanditiis dolores! Doloribus, consectetur. Quae repudiandae porro rerum corporis voluptatem, assumenda vitae ad totam quasi voluptatum pariatur dignissimos praesentium soluta dicta provident! Ea provident vero excepturi perspiciatis sunt quidem alias, officiis eveniet. Incidunt voluptate sunt, quasi veritatis eos, facilis nemo consequatur, excepturi voluptas temporibus cupiditate quos magni voluptatum id! Ea quos culpa eveniet! Sequi iure magnam velit, voluptatum molestiae sed, soluta perspiciatis eveniet aliquam repellat nam distinctio corrupti quidem eius eligendi amet harum tempora nesciunt cupiditate culpa odit neque inventore assumenda debitis! Minima voluptatibus autem vel omnis tempora exercitationem ex error dolor sequi, quaerat aliquid nihil sit debitis porro numquam. Quibusdam soluta repellendus nemo ipsam reiciendis quasi consectetur ab. Eius et nesciunt, dolores ullam ad, delectus nihil sapiente iure perspiciatis distinctio quibusdam repudiandae. Atque libero excepturi cumque, fugit cum facilis asperiores cupiditate iusto ratione reiciendis aliquam labore est mollitia velit corrupti perferendis exercitationem. Fugit, amet veritatis? Adipisci incidunt ab explicabo ut dolores dolorum deleniti recusandae, laboriosam iure pariatur possimus, animi libero vero, ea tenetur. Beatae porro labore rerum eligendi ea consequuntur voluptas voluptatem voluptate incidunt nostrum. Autem, quaerat quidem. Consectetur ipsum accusantium, ipsam neque ut expedita totam quisquam adipisci quia! Aliquam et modi soluta ad dolores? Optio doloribus unde eveniet obcaecati veritatis dicta possimus enim amet perspiciatis ratione repellendus reprehenderit, numquam voluptatibus labore, magnam iusto aperiam magni quos laudantium cumque?"
    },
    {
        _id: "64ca92788ff1ae63f13b1f6c",
        title: "Its notice title",
        disc: "Lorem ieimus enim amet perspiciatis ratione repellendus reprehenderit, numquam voluptatibus labore, magnam iusto aperiam magni quos laudantium cumque?"
    },
    {
        _id: "64ca92788ff1ae63f13b1f6c",
        title: "Its notice title",
        disc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magni facere itaque facilis laboriosam explicabo eligendi, praesentium nulla esse quos atque veritatis fugit accusantium debitis cupiditate obcaecati possimus dignissimos incidunt molestiae quis repellat eum eos est. Tempore veritatis ratione atque, consequuntur repellendus cumque similique sequi? Exercitationem aut nulla provident suscipit eaque, ullam qui dolor earum. Error nihil culpa, maxime pariatur nobis ab maiores corrupti explicabo et dicta iste doloribus ipsum iusto ut soluta eum laboriosam provident eos architecto totam tempore incidunt blanditiis dolores! Doloribus, consectetur. Quae repudiandae porro rerum corporis voluptatem, assumenda vitae ad totam quasi voluptatum pariatur dignissimos praesentium soluta dicta provident! Ea provident vero excepturi perspiciatis sunt quidem alias, officiis eveniet. Incidunt voluptate sunt, quasi veritatis eos, facilis nemo consequatur, excepturi voluptas temporibus cupiditate quos magni voluptatum id! Ea quos culpa eveniet! Sequi iure magnam velit, voluptatum molestiae sed, soluta perspiciatis eveniet aliquam repellat nam distinctio corrupti quidem eius eligendi amet harum tempora nesciunt cupiditate culpa odit neque inventore assumenda debitis! Minima voluptatibus autem vel omnis tempora exercitationem ex error dolor sequi, quaerat aliquid nihil sit debitis porro numquam. Quibusdam soluta repellendus nemo ipsam reiciendis quasi consectetur ab. Eius et nesciunt, dolores ullam ad, delectus nihil sapiente iure perspiciatis distinctio quibusdam repudiandae. Atque libero excepturi cumque, fugit cum facilis asperiores cupiditate iusto ratione reiciendis aliquam labore est mollitia velit corrupti perferendis exercitationem. Fugit, amet veritatis? Adipisci incidunt ab explicabo ut dolores dolorum deleniti recusandae, laboriosam iure pariatur possimus, animi libero vero, ea tenetur. Beatae porro labore rerum eligendi ea consequuntur voluptas voluptatem voluptate incidunt nostrum. Autem, quaerat quidem. Consectetur ipsum accusantium, ipsam neque ut expedita totam quisquam adipisci quia! Aliquam et modi soluta ad dolores? Optio doloribus unde eveniet obcaecati veritatis dicta possimus enim amet perspiciatis ratione repellendus reprehenderit, numquam voluptatibus labore, magnam iusto aperiam magni quos laudantium cumque?"
    },
    {
        _id: "64ca92788ff1ae63f13b1f6c",
        title: "Its notice title",
        disc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magni facere itaque facilis laboriosam explicabo eligendi, praesentium nulla esse quos atque veritatis fugit accusantium debitis cupiditate obcaecati possimus dignissimos incidunt molestiae quis repellat eum eos est. Tempore veritatis ratione atque, consequuntur repellendus cumque similique sequi? Exercitationem aut nulla provident suscipit eaque, ullam qui dolor earum. Error nihil culpa, maxime pariatur nobis ab maiores corrupti explicabo et dicta iste doloribus ipsum iusto ut soluta eum laboriosam provident eos architecto totam tempore incidunt blanditiis dolores! Doloribus, consectetur. Quae repudiandae porro rerum corporis voluptatem, assumenda vitae ad totam quasi voluptatum pariatur dignissimos praesentium soluta dicta provident! Ea provident vero excepturi perspiciatis sunt quidem alias, officiis eveniet. Incidunt voluptate sunt, quasi veritatis eos, facilis nemo consequatur, excepturi voluptas temporibus cupiditate quos magni voluptatum id! Ea quos culpa eveniet! Sequi iure magnam velit, voluptatum molestiae sed, soluta perspiciatis eveniet aliquam repellat nam distinctio corrupti quidem eius eligendi amet harum tempora nesciunt cupiditate culpa odit neque inventore assumenda debitis! Minima voluptatibus autem vel omnis tempora exercitationem ex error dolor sequi, quaerat aliquid nihil sit debitis porro numquam. Quibusdam soluta repellendus nemo ipsam reiciendis quasi consectetur ab. Eius et nesciunt, dolores ullam ad, delectus nihil sapiente iure perspiciatis distinctio quibusdam repudiandae. Atque libero excepturi cumque, fugit cum facilis asperiores cupiditate iusto ratione reiciendis aliquam labore est mollitia velit corrupti perferendis exercitationem. Fugit, amet veritatis? Adipisci incidunt ab explicabo ut dolores dolorum deleniti recusandae, laboriosam iure pariatur possimus, animi libero vero, ea tenetur. Beatae porro labore rerum eligendi ea consequuntur voluptas voluptatem voluptate incidunt nostrum. Autem, quaerat quidem. Consectetur ipsum accusantium, ipsam neque ut expedita totam quisquam adipisci quia! Aliquam et modi soluta ad dolores? Optio doloribus unde eveniet obcaecati veritatis dicta possimus enim amet perspiciatis ratione repellendus reprehenderit, numquam voluptatibus labore, magnam iusto aperiam magni quos laudantium cumque?"
    },
    {
        _id: "64ca92788ff1ae63f13b1f6c",
        title: "Its notice title",
        disc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magni facere itaque facilis laboriosam explicabo eligendi, praesentium nulla esse quos atque veritatis fugit accusantium debitis cupiditate obcaecati possimus dignissimos incidunt molestiae quis repellat eum eos est. Tempore veritatis ratione atque, consequuntur repellendus cumque similique sequi? Exercitationem aut nulla provident suscipit eaque, ullam qui dolor earum. Error nihil culpa, maxime pariatur nobis ab maiores corrupti explicabo et dicta iste doloribus ipsum iusto ut soluta eum laboriosam provident eos architecto totam tempore incidunt blanditiis dolores! Doloribus, consectetur. Quae repudiandae porro rerum corporis voluptatem, assumenda vitae ad totam quasi voluptatum pariatur dignissimos praesentium soluta dicta provident! Ea provident vero excepturi perspiciatis sunt quidem alias, officiis eveniet. Incidunt voluptate sunt, quasi veritatis eos, facilis nemo consequatur, excepturi voluptas temporibus cupiditate quos magni voluptatum id! Ea quos culpa eveniet! Sequi iure magnam velit, voluptatum molestiae sed, soluta perspiciatis eveniet aliquam repellat nam distinctio corrupti quidem eius eligendi amet harum tempora nesciunt cupiditate culpa odit neque inventore assumenda debitis! Minima voluptatibus autem vel omnis tempora exercitationem ex error dolor sequi, quaerat aliquid nihil sit debitis porro numquam. Quibusdam soluta repellendus nemo ipsam reiciendis quasi consectetur ab. Eius et nesciunt, dolores ullam ad, delectus nihil sapiente iure perspiciatis distinctio quibusdam repudiandae. Atque libero excepturi cumque, fugit cum facilis asperiores cupiditate iusto ratione reiciendis aliquam labore est mollitia velit corrupti perferendis exercitationem. Fugit, amet veritatis? Adipisci incidunt ab explicabo ut dolores dolorum deleniti recusandae, laboriosam iure pariatur possimus, animi libero vero, ea tenetur. Beatae porro labore rerum eligendi ea consequuntur voluptas voluptatem voluptate incidunt nostrum. Autem, quaerat quidem. Consectetur ipsum accusantium, ipsam neque ut expedita totam quisquam adipisci quia! Aliquam et modi soluta ad dolores? Optio doloribus unde eveniet obcaecati veritatis dicta possimus enim amet perspiciatis ratione repellendus reprehenderit, numquam voluptatibus labore, magnam iusto aperiam magni quos laudantium cumque?"
    },
    {
        _id: "64ca92788ff1ae63f13b1f6c",
        title: "Its notice title",
        disc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magni facere itaque facilis laboriosam explicabo eligendi, praesentium nulla esse quos atque veritatis fugit accusantium debitis cupiditate obcaecati possimus dignissimos incidunt molestiae quis repellat eum eos est. Tempore veritatis ratione atque, consequuntur repellendus cumque similique sequi? Exercitationem aut nulla provident suscipit eaque, ullam qui dolor earum. Error nihil culpa, maxime pariatur nobis ab maiores corrupti explicabo et dicta iste doloribus ipsum iusto ut soluta eum laboriosam provident eos architecto totam tempore incidunt blanditiis dolores! Doloribus, consectetur. Quae repudiandae porro rerum corporis voluptatem, assumenda vitae ad totam quasi voluptatum pariatur dignissimos praesentium soluta dicta provident! Ea provident vero excepturi perspiciatis sunt quidem alias, officiis eveniet. Incidunt voluptate sunt, quasi veritatis eos, facilis nemo consequatur, excepturi voluptas temporibus cupiditate quos magni voluptatum id! Ea quos culpa eveniet! Sequi iure magnam velit, voluptatum molestiae sed, soluta perspiciatis eveniet aliquam repellat nam distinctio corrupti quidem eius eligendi amet harum tempora nesciunt cupiditate culpa odit neque inventore assumenda debitis! Minima voluptatibus autem vel omnis tempora exercitationem ex error dolor sequi, quaerat aliquid nihil sit debitis porro numquam. Quibusdam soluta repellendus nemo ipsam reiciendis quasi consectetur ab. Eius et nesciunt, dolores ullam ad, delectus nihil sapiente iure perspiciatis distinctio quibusdam repudiandae. Atque libero excepturi cumque, fugit cum facilis asperiores cupiditate iusto ratione reiciendis aliquam labore est mollitia velit corrupti perferendis exercitationem. Fugit, amet veritatis? Adipisci incidunt ab explicabo ut dolores dolorum deleniti recusandae, laboriosam iure pariatur possimus, animi libero vero, ea tenetur. Beatae porro labore rerum eligendi ea consequuntur voluptas voluptatem voluptate incidunt nostrum. Autem, quaerat quidem. Consectetur ipsum accusantium, ipsam neque ut expedita totam quisquam adipisci quia! Aliquam et modi soluta ad dolores? Optio doloribus unde eveniet obcaecati veritatis dicta possimus enim amet perspiciatis ratione repellendus reprehenderit, numquam voluptatibus labore, magnam iusto aperiam magni quos laudantium cumque?"
    },
    {
        _id: "64ca92788ff1ae63f13b1f6c",
        title: "Its notice title",
        disc: "Lorem ieimus enim amet perspiciatis ratione repellendus reprehenderit, numquam voluptatibus labore, magnam iusto aperiam magni quos laudantium cumque?"
    },
    {
        _id: "64ca92788ff1ae63f13b1f6c",
        title: "Its notice title",
        disc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magni facere itaque facilis laboriosam explicabo eligendi, praesentium nulla esse quos atque veritatis fugit accusantium debitis cupiditate obcaecati possimus dignissimos incidunt molestiae quis repellat eum eos est. Tempore veritatis ratione atque, consequuntur repellendus cumque similique sequi? Exercitationem aut nulla provident suscipit eaque, ullam qui dolor earum. Error nihil culpa, maxime pariatur nobis ab maiores corrupti explicabo et dicta iste doloribus ipsum iusto ut soluta eum laboriosam provident eos architecto totam tempore incidunt blanditiis dolores! Doloribus, consectetur. Quae repudiandae porro rerum corporis voluptatem, assumenda vitae ad totam quasi voluptatum pariatur dignissimos praesentium soluta dicta provident! Ea provident vero excepturi perspiciatis sunt quidem alias, officiis eveniet. Incidunt voluptate sunt, quasi veritatis eos, facilis nemo consequatur, excepturi voluptas temporibus cupiditate quos magni voluptatum id! Ea quos culpa eveniet! Sequi iure magnam velit, voluptatum molestiae sed, soluta perspiciatis eveniet aliquam repellat nam distinctio corrupti quidem eius eligendi amet harum tempora nesciunt cupiditate culpa odit neque inventore assumenda debitis! Minima voluptatibus autem vel omnis tempora exercitationem ex error dolor sequi, quaerat aliquid nihil sit debitis porro numquam. Quibusdam soluta repellendus nemo ipsam reiciendis quasi consectetur ab. Eius et nesciunt, dolores ullam ad, delectus nihil sapiente iure perspiciatis distinctio quibusdam repudiandae. Atque libero excepturi cumque, fugit cum facilis asperiores cupiditate iusto ratione reiciendis aliquam labore est mollitia velit corrupti perferendis exercitationem. Fugit, amet veritatis? Adipisci incidunt ab explicabo ut dolores dolorum deleniti recusandae, laboriosam iure pariatur possimus, animi libero vero, ea tenetur. Beatae porro labore rerum eligendi ea consequuntur voluptas voluptatem voluptate incidunt nostrum. Autem, quaerat quidem. Consectetur ipsum accusantium, ipsam neque ut expedita totam quisquam adipisci quia! Aliquam et modi soluta ad dolores? Optio doloribus unde eveniet obcaecati veritatis dicta possimus enim amet perspiciatis ratione repellendus reprehenderit, numquam voluptatibus labore, magnam iusto aperiam magni quos laudantium cumque?"
    },
    {
        _id: "64ca92788ff1ae63f13b1f6c",
        title: "Its notice title",
        disc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magni facere itaque facilis laboriosam explicabo eligendi, praesentium nulla esse quos atque veritatis fugit accusantium debitis cupiditate obcaecati possimus dignissimos incidunt molestiae quis repellat eum eos est. Tempore veritatis ratione atque, consequuntur repellendus cumque similique sequi? Exercitationem aut nulla provident suscipit eaque, ullam qui dolor earum. Error nihil culpa, maxime pariatur nobis ab maiores corrupti explicabo et dicta iste doloribus ipsum iusto ut soluta eum laboriosam provident eos architecto totam tempore incidunt blanditiis dolores! Doloribus, consectetur. Quae repudiandae porro rerum corporis voluptatem, assumenda vitae ad totam quasi voluptatum pariatur dignissimos praesentium soluta dicta provident! Ea provident vero excepturi perspiciatis sunt quidem alias, officiis eveniet. Incidunt voluptate sunt, quasi veritatis eos, facilis nemo consequatur, excepturi voluptas temporibus cupiditate quos magni voluptatum id! Ea quos culpa eveniet! Sequi iure magnam velit, voluptatum molestiae sed, soluta perspiciatis eveniet aliquam repellat nam distinctio corrupti quidem eius eligendi amet harum tempora nesciunt cupiditate culpa odit neque inventore assumenda debitis! Minima voluptatibus autem vel omnis tempora exercitationem ex error dolor sequi, quaerat aliquid nihil sit debitis porro numquam. Quibusdam soluta repellendus nemo ipsam reiciendis quasi consectetur ab. Eius et nesciunt, dolores ullam ad, delectus nihil sapiente iure perspiciatis distinctio quibusdam repudiandae. Atque libero excepturi cumque, fugit cum facilis asperiores cupiditate iusto ratione reiciendis aliquam labore est mollitia velit corrupti perferendis exercitationem. Fugit, amet veritatis? Adipisci incidunt ab explicabo ut dolores dolorum deleniti recusandae, laboriosam iure pariatur possimus, animi libero vero, ea tenetur. Beatae porro labore rerum eligendi ea consequuntur voluptas voluptatem voluptate incidunt nostrum. Autem, quaerat quidem. Consectetur ipsum accusantium, ipsam neque ut expedita totam quisquam adipisci quia! Aliquam et modi soluta ad dolores? Optio doloribus unde eveniet obcaecati veritatis dicta possimus enim amet perspiciatis ratione repellendus reprehenderit, numquam voluptatibus labore, magnam iusto aperiam magni quos laudantium cumque?"
    },
    {
        _id: "64ca92788ff1ae63f13b1f6c",
        title: "Its notice title",
        disc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magni facere itaque facilis laboriosam explicabo eligendi, praesentium nulla esse quos atque veritatis fugit accusantium debitis cupiditate obcaecati possimus dignissimos incidunt molestiae quis repellat eum eos est. Tempore veritatis ratione atque, consequuntur repellendus cumque similique sequi? Exercitationem aut nulla provident suscipit eaque, ullam qui dolor earum. Error nihil culpa, maxime pariatur nobis ab maiores corrupti explicabo et dicta iste doloribus ipsum iusto ut soluta eum laboriosam provident eos architecto totam tempore incidunt blanditiis dolores! Doloribus, consectetur. Quae repudiandae porro rerum corporis voluptatem, assumenda vitae ad totam quasi voluptatum pariatur dignissimos praesentium soluta dicta provident! Ea provident vero excepturi perspiciatis sunt quidem alias, officiis eveniet. Incidunt voluptate sunt, quasi veritatis eos, facilis nemo consequatur, excepturi voluptas temporibus cupiditate quos magni voluptatum id! Ea quos culpa eveniet! Sequi iure magnam velit, voluptatum molestiae sed, soluta perspiciatis eveniet aliquam repellat nam distinctio corrupti quidem eius eligendi amet harum tempora nesciunt cupiditate culpa odit neque inventore assumenda debitis! Minima voluptatibus autem vel omnis tempora exercitationem ex error dolor sequi, quaerat aliquid nihil sit debitis porro numquam. Quibusdam soluta repellendus nemo ipsam reiciendis quasi consectetur ab. Eius et nesciunt, dolores ullam ad, delectus nihil sapiente iure perspiciatis distinctio quibusdam repudiandae. Atque libero excepturi cumque, fugit cum facilis asperiores cupiditate iusto ratione reiciendis aliquam labore est mollitia velit corrupti perferendis exercitationem. Fugit, amet veritatis? Adipisci incidunt ab explicabo ut dolores dolorum deleniti recusandae, laboriosam iure pariatur possimus, animi libero vero, ea tenetur. Beatae porro labore rerum eligendi ea consequuntur voluptas voluptatem voluptate incidunt nostrum. Autem, quaerat quidem. Consectetur ipsum accusantium, ipsam neque ut expedita totam quisquam adipisci quia! Aliquam et modi soluta ad dolores? Optio doloribus unde eveniet obcaecati veritatis dicta possimus enim amet perspiciatis ratione repellendus reprehenderit, numquam voluptatibus labore, magnam iusto aperiam magni quos laudantium cumque?"
    },
    {
        _id: "64ca92788ff1ae63f13b1f6c",
        title: "Its notice title",
        disc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magni facere itaque facilis laboriosam explicabo eligendi, praesentium nulla esse quos atque veritatis fugit accusantium debitis cupiditate obcaecati possimus dignissimos incidunt molestiae quis repellat eum eos est. Tempore veritatis ratione atque, consequuntur repellendus cumque similique sequi? Exercitationem aut nulla provident suscipit eaque, ullam qui dolor earum. Error nihil culpa, maxime pariatur nobis ab maiores corrupti explicabo et dicta iste doloribus ipsum iusto ut soluta eum laboriosam provident eos architecto totam tempore incidunt blanditiis dolores! Doloribus, consectetur. Quae repudiandae porro rerum corporis voluptatem, assumenda vitae ad totam quasi voluptatum pariatur dignissimos praesentium soluta dicta provident! Ea provident vero excepturi perspiciatis sunt quidem alias, officiis eveniet. Incidunt voluptate sunt, quasi veritatis eos, facilis nemo consequatur, excepturi voluptas temporibus cupiditate quos magni voluptatum id! Ea quos culpa eveniet! Sequi iure magnam velit, voluptatum molestiae sed, soluta perspiciatis eveniet aliquam repellat nam distinctio corrupti quidem eius eligendi amet harum tempora nesciunt cupiditate culpa odit neque inventore assumenda debitis! Minima voluptatibus autem vel omnis tempora exercitationem ex error dolor sequi, quaerat aliquid nihil sit debitis porro numquam. Quibusdam soluta repellendus nemo ipsam reiciendis quasi consectetur ab. Eius et nesciunt, dolores ullam ad, delectus nihil sapiente iure perspiciatis distinctio quibusdam repudiandae. Atque libero excepturi cumque, fugit cum facilis asperiores cupiditate iusto ratione reiciendis aliquam labore est mollitia velit corrupti perferendis exercitationem. Fugit, amet veritatis? Adipisci incidunt ab explicabo ut dolores dolorum deleniti recusandae, laboriosam iure pariatur possimus, animi libero vero, ea tenetur. Beatae porro labore rerum eligendi ea consequuntur voluptas voluptatem voluptate incidunt nostrum. Autem, quaerat quidem. Consectetur ipsum accusantium, ipsam neque ut expedita totam quisquam adipisci quia! Aliquam et modi soluta ad dolores? Optio doloribus unde eveniet obcaecati veritatis dicta possimus enim amet perspiciatis ratione repellendus reprehenderit, numquam voluptatibus labore, magnam iusto aperiam magni quos laudantium cumque?"
    },
    {
        _id: "64ca92788ff1ae63f13b1f6c",
        title: "Its notice title",
        disc: "Lorem ieimus enim amet perspiciatis ratione repellendus reprehenderit, numquam voluptatibus labore, magnam iusto aperiam magni quos laudantium cumque?"
    },
    {
        _id: "64ca92788ff1ae63f13b1f6c",
        title: "Its notice title",
        disc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magni facere itaque facilis laboriosam explicabo eligendi, praesentium nulla esse quos atque veritatis fugit accusantium debitis cupiditate obcaecati possimus dignissimos incidunt molestiae quis repellat eum eos est. Tempore veritatis ratione atque, consequuntur repellendus cumque similique sequi? Exercitationem aut nulla provident suscipit eaque, ullam qui dolor earum. Error nihil culpa, maxime pariatur nobis ab maiores corrupti explicabo et dicta iste doloribus ipsum iusto ut soluta eum laboriosam provident eos architecto totam tempore incidunt blanditiis dolores! Doloribus, consectetur. Quae repudiandae porro rerum corporis voluptatem, assumenda vitae ad totam quasi voluptatum pariatur dignissimos praesentium soluta dicta provident! Ea provident vero excepturi perspiciatis sunt quidem alias, officiis eveniet. Incidunt voluptate sunt, quasi veritatis eos, facilis nemo consequatur, excepturi voluptas temporibus cupiditate quos magni voluptatum id! Ea quos culpa eveniet! Sequi iure magnam velit, voluptatum molestiae sed, soluta perspiciatis eveniet aliquam repellat nam distinctio corrupti quidem eius eligendi amet harum tempora nesciunt cupiditate culpa odit neque inventore assumenda debitis! Minima voluptatibus autem vel omnis tempora exercitationem ex error dolor sequi, quaerat aliquid nihil sit debitis porro numquam. Quibusdam soluta repellendus nemo ipsam reiciendis quasi consectetur ab. Eius et nesciunt, dolores ullam ad, delectus nihil sapiente iure perspiciatis distinctio quibusdam repudiandae. Atque libero excepturi cumque, fugit cum facilis asperiores cupiditate iusto ratione reiciendis aliquam labore est mollitia velit corrupti perferendis exercitationem. Fugit, amet veritatis? Adipisci incidunt ab explicabo ut dolores dolorum deleniti recusandae, laboriosam iure pariatur possimus, animi libero vero, ea tenetur. Beatae porro labore rerum eligendi ea consequuntur voluptas voluptatem voluptate incidunt nostrum. Autem, quaerat quidem. Consectetur ipsum accusantium, ipsam neque ut expedita totam quisquam adipisci quia! Aliquam et modi soluta ad dolores? Optio doloribus unde eveniet obcaecati veritatis dicta possimus enim amet perspiciatis ratione repellendus reprehenderit, numquam voluptatibus labore, magnam iusto aperiam magni quos laudantium cumque?"
    },
    {
        _id: "64ca92788ff1ae63f13b1f6c",
        title: "Its notice title",
        disc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magni facere itaque facilis laboriosam explicabo eligendi, praesentium nulla esse quos atque veritatis fugit accusantium debitis cupiditate obcaecati possimus dignissimos incidunt molestiae quis repellat eum eos est. Tempore veritatis ratione atque, consequuntur repellendus cumque similique sequi? Exercitationem aut nulla provident suscipit eaque, ullam qui dolor earum. Error nihil culpa, maxime pariatur nobis ab maiores corrupti explicabo et dicta iste doloribus ipsum iusto ut soluta eum laboriosam provident eos architecto totam tempore incidunt blanditiis dolores! Doloribus, consectetur. Quae repudiandae porro rerum corporis voluptatem, assumenda vitae ad totam quasi voluptatum pariatur dignissimos praesentium soluta dicta provident! Ea provident vero excepturi perspiciatis sunt quidem alias, officiis eveniet. Incidunt voluptate sunt, quasi veritatis eos, facilis nemo consequatur, excepturi voluptas temporibus cupiditate quos magni voluptatum id! Ea quos culpa eveniet! Sequi iure magnam velit, voluptatum molestiae sed, soluta perspiciatis eveniet aliquam repellat nam distinctio corrupti quidem eius eligendi amet harum tempora nesciunt cupiditate culpa odit neque inventore assumenda debitis! Minima voluptatibus autem vel omnis tempora exercitationem ex error dolor sequi, quaerat aliquid nihil sit debitis porro numquam. Quibusdam soluta repellendus nemo ipsam reiciendis quasi consectetur ab. Eius et nesciunt, dolores ullam ad, delectus nihil sapiente iure perspiciatis distinctio quibusdam repudiandae. Atque libero excepturi cumque, fugit cum facilis asperiores cupiditate iusto ratione reiciendis aliquam labore est mollitia velit corrupti perferendis exercitationem. Fugit, amet veritatis? Adipisci incidunt ab explicabo ut dolores dolorum deleniti recusandae, laboriosam iure pariatur possimus, animi libero vero, ea tenetur. Beatae porro labore rerum eligendi ea consequuntur voluptas voluptatem voluptate incidunt nostrum. Autem, quaerat quidem. Consectetur ipsum accusantium, ipsam neque ut expedita totam quisquam adipisci quia! Aliquam et modi soluta ad dolores? Optio doloribus unde eveniet obcaecati veritatis dicta possimus enim amet perspiciatis ratione repellendus reprehenderit, numquam voluptatibus labore, magnam iusto aperiam magni quos laudantium cumque?"
    },
    {
        _id: "64ca92788ff1ae63f13b1f6c",
        title: "Its notice title",
        disc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magni facere itaque facilis laboriosam explicabo eligendi, praesentium nulla esse quos atque veritatis fugit accusantium debitis cupiditate obcaecati possimus dignissimos incidunt molestiae quis repellat eum eos est. Tempore veritatis ratione atque, consequuntur repellendus cumque similique sequi? Exercitationem aut nulla provident suscipit eaque, ullam qui dolor earum. Error nihil culpa, maxime pariatur nobis ab maiores corrupti explicabo et dicta iste doloribus ipsum iusto ut soluta eum laboriosam provident eos architecto totam tempore incidunt blanditiis dolores! Doloribus, consectetur. Quae repudiandae porro rerum corporis voluptatem, assumenda vitae ad totam quasi voluptatum pariatur dignissimos praesentium soluta dicta provident! Ea provident vero excepturi perspiciatis sunt quidem alias, officiis eveniet. Incidunt voluptate sunt, quasi veritatis eos, facilis nemo consequatur, excepturi voluptas temporibus cupiditate quos magni voluptatum id! Ea quos culpa eveniet! Sequi iure magnam velit, voluptatum molestiae sed, soluta perspiciatis eveniet aliquam repellat nam distinctio corrupti quidem eius eligendi amet harum tempora nesciunt cupiditate culpa odit neque inventore assumenda debitis! Minima voluptatibus autem vel omnis tempora exercitationem ex error dolor sequi, quaerat aliquid nihil sit debitis porro numquam. Quibusdam soluta repellendus nemo ipsam reiciendis quasi consectetur ab. Eius et nesciunt, dolores ullam ad, delectus nihil sapiente iure perspiciatis distinctio quibusdam repudiandae. Atque libero excepturi cumque, fugit cum facilis asperiores cupiditate iusto ratione reiciendis aliquam labore est mollitia velit corrupti perferendis exercitationem. Fugit, amet veritatis? Adipisci incidunt ab explicabo ut dolores dolorum deleniti recusandae, laboriosam iure pariatur possimus, animi libero vero, ea tenetur. Beatae porro labore rerum eligendi ea consequuntur voluptas voluptatem voluptate incidunt nostrum. Autem, quaerat quidem. Consectetur ipsum accusantium, ipsam neque ut expedita totam quisquam adipisci quia! Aliquam et modi soluta ad dolores? Optio doloribus unde eveniet obcaecati veritatis dicta possimus enim amet perspiciatis ratione repellendus reprehenderit, numquam voluptatibus labore, magnam iusto aperiam magni quos laudantium cumque?"
    },
    {
        _id: "64ca92788ff1ae63f13b1f6c",
        title: "Its notice title",
        disc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magni facere itaque facilis laboriosam explicabo eligendi, praesentium nulla esse quos atque veritatis fugit accusantium debitis cupiditate obcaecati possimus dignissimos incidunt molestiae quis repellat eum eos est. Tempore veritatis ratione atque, consequuntur repellendus cumque similique sequi? Exercitationem aut nulla provident suscipit eaque, ullam qui dolor earum. Error nihil culpa, maxime pariatur nobis ab maiores corrupti explicabo et dicta iste doloribus ipsum iusto ut soluta eum laboriosam provident eos architecto totam tempore incidunt blanditiis dolores! Doloribus, consectetur. Quae repudiandae porro rerum corporis voluptatem, assumenda vitae ad totam quasi voluptatum pariatur dignissimos praesentium soluta dicta provident! Ea provident vero excepturi perspiciatis sunt quidem alias, officiis eveniet. Incidunt voluptate sunt, quasi veritatis eos, facilis nemo consequatur, excepturi voluptas temporibus cupiditate quos magni voluptatum id! Ea quos culpa eveniet! Sequi iure magnam velit, voluptatum molestiae sed, soluta perspiciatis eveniet aliquam repellat nam distinctio corrupti quidem eius eligendi amet harum tempora nesciunt cupiditate culpa odit neque inventore assumenda debitis! Minima voluptatibus autem vel omnis tempora exercitationem ex error dolor sequi, quaerat aliquid nihil sit debitis porro numquam. Quibusdam soluta repellendus nemo ipsam reiciendis quasi consectetur ab. Eius et nesciunt, dolores ullam ad, delectus nihil sapiente iure perspiciatis distinctio quibusdam repudiandae. Atque libero excepturi cumque, fugit cum facilis asperiores cupiditate iusto ratione reiciendis aliquam labore est mollitia velit corrupti perferendis exercitationem. Fugit, amet veritatis? Adipisci incidunt ab explicabo ut dolores dolorum deleniti recusandae, laboriosam iure pariatur possimus, animi libero vero, ea tenetur. Beatae porro labore rerum eligendi ea consequuntur voluptas voluptatem voluptate incidunt nostrum. Autem, quaerat quidem. Consectetur ipsum accusantium, ipsam neque ut expedita totam quisquam adipisci quia! Aliquam et modi soluta ad dolores? Optio doloribus unde eveniet obcaecati veritatis dicta possimus enim amet perspiciatis ratione repellendus reprehenderit, numquam voluptatibus labore, magnam iusto aperiam magni quos laudantium cumque?"
    },
    {
        _id: "64ca92788ff1ae63f13b1f6c",
        title: "Its notice title",
        disc: "Lorem ieimus enim amet perspiciatis ratione repellendus reprehenderit, numquam voluptatibus labore, magnam iusto aperiam magni quos laudantium cumque?"
    },
    {
        _id: "64ca92788ff1ae63f13b1f6c",
        title: "General Notice Regarding Seminar on Higher Education in Russia",
        disc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magni facere itaque facilis laboriosam explicabo eligendi, praesentium nulla esse quos atque veritatis fugit accusantium debitis cupiditate obcaecati possimus dignissimos incidunt molestiae quis repellat eum eos est. Tempore veritatis ratione atque, consequuntur repellendus cumque similique sequi? Exercitationem aut nulla provident suscipit eaque, ullam qui dolor earum. Error nihil culpa, maxime pariatur nobis ab maiores corrupti explicabo et dicta iste doloribus ipsum iusto ut soluta eum laboriosam provident eos architecto totam tempore incidunt blanditiis dolores! Doloribus, consectetur. Quae repudiandae porro rerum corporis voluptatem, assumenda vitae ad totam quasi voluptatum pariatur dignissimos praesentium soluta dicta provident! Ea provident vero excepturi perspiciatis sunt quidem alias, officiis eveniet. Incidunt voluptate sunt, quasi veritatis eos, facilis nemo consequatur, excepturi voluptas temporibus cupiditate quos magni voluptatum id! Ea quos culpa eveniet! Sequi iure magnam velit, voluptatum molestiae sed, soluta perspiciatis eveniet aliquam repellat nam distinctio corrupti quidem eius eligendi amet harum tempora nesciunt cupiditate culpa odit neque inventore assumenda debitis! Minima voluptatibus autem vel omnis tempora exercitationem ex error dolor sequi, quaerat aliquid nihil sit debitis porro numquam. Quibusdam soluta repellendus nemo ipsam reiciendis quasi consectetur ab. Eius et nesciunt, dolores ullam ad, delectus nihil sapiente iure perspiciatis distinctio quibusdam repudiandae. Atque libero excepturi cumque, fugit cum facilis asperiores cupiditate iusto ratione reiciendis aliquam labore est mollitia velit corrupti perferendis exercitationem. Fugit, amet veritatis? Adipisci incidunt ab explicabo ut dolores dolorum deleniti recusandae, laboriosam iure pariatur possimus, animi libero vero, ea tenetur. Beatae porro labore rerum eligendi ea consequuntur voluptas voluptatem voluptate incidunt nostrum. Autem, quaerat quidem. Consectetur ipsum accusantium, ipsam neque ut expedita totam quisquam adipisci quia! Aliquam et modi soluta ad dolores? Optio doloribus unde eveniet obcaecati veritatis dicta possimus enim amet perspiciatis ratione repellendus reprehenderit, numquam voluptatibus labore, magnam iusto aperiam magni quos laudantium cumque?"
    },
    {
        _id: "64ca92788ff1ae63f13b1f6c",
        title: "Schedule of Weekly Examination",
        disc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magni facere itaque facilis laboriosam explicabo eligendi, praesentium nulla esse quos atque veritatis fugit accusantium debitis cupiditate obcaecati possimus dignissimos incidunt molestiae quis repellat eum eos est. Tempore veritatis ratione atque, consequuntur repellendus cumque similique sequi? Exercitationem aut nulla provident suscipit eaque, ullam qui dolor earum. Error nihil culpa, maxime pariatur nobis ab maiores corrupti explicabo et dicta iste doloribus ipsum iusto ut soluta eum laboriosam provident eos architecto totam tempore incidunt blanditiis dolores! Doloribus, consectetur. Quae repudiandae porro rerum corporis voluptatem, assumenda vitae ad totam quasi voluptatum pariatur dignissimos praesentium soluta dicta provident! Ea provident vero excepturi perspiciatis sunt quidem alias, officiis eveniet. Incidunt voluptate sunt, quasi veritatis eos, facilis nemo consequatur, excepturi voluptas temporibus cupiditate quos magni voluptatum id! Ea quos culpa eveniet! Sequi iure magnam velit, voluptatum molestiae sed, soluta perspiciatis eveniet aliquam repellat nam distinctio corrupti quidem eius eligendi amet harum tempora nesciunt cupiditate culpa odit neque inventore assumenda debitis! Minima voluptatibus autem vel omnis tempora exercitationem ex error dolor sequi, quaerat aliquid nihil sit debitis porro numquam. Quibusdam soluta repellendus nemo ipsam reiciendis quasi consectetur ab. Eius et nesciunt, dolores ullam ad, delectus nihil sapiente iure perspiciatis distinctio quibusdam repudiandae. Atque libero excepturi cumque, fugit cum facilis asperiores cupiditate iusto ratione reiciendis aliquam labore est mollitia velit corrupti perferendis exercitationem. Fugit, amet veritatis? Adipisci incidunt ab explicabo ut dolores dolorum deleniti recusandae, laboriosam iure pariatur possimus, animi libero vero, ea tenetur. Beatae porro labore rerum eligendi ea consequuntur voluptas voluptatem voluptate incidunt nostrum. Autem, quaerat quidem. Consectetur ipsum accusantium, ipsam neque ut expedita totam quisquam adipisci quia! Aliquam et modi soluta ad dolores? Optio doloribus unde eveniet obcaecati veritatis dicta possimus enim amet perspiciatis ratione repellendus reprehenderit, numquam voluptatibus labore, magnam iusto aperiam magni quos laudantium cumque?"
    },
    {
        _id: "64ca92788ff1ae63f13b1f6c",
        title: "Payment Notice for All students",
        disc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magni facere itaque facilis laboriosam explicabo eligendi, praesentium nulla esse quos atque veritatis fugit accusantium debitis cupiditate obcaecati possimus dignissimos incidunt molestiae quis repellat eum eos est. Tempore veritatis ratione atque, consequuntur repellendus cumque similique sequi? Exercitationem aut nulla provident suscipit eaque, ullam qui dolor earum. Error nihil culpa, maxime pariatur nobis ab maiores corrupti explicabo et dicta iste doloribus ipsum iusto ut soluta eum laboriosam provident eos architecto totam tempore incidunt blanditiis dolores! Doloribus, consectetur. Quae repudiandae porro rerum corporis voluptatem, assumenda vitae ad totam quasi voluptatum pariatur dignissimos praesentium soluta dicta provident! Ea provident vero excepturi perspiciatis sunt quidem alias, officiis eveniet. Incidunt voluptate sunt, quasi veritatis eos, facilis nemo consequatur, excepturi voluptas temporibus cupiditate quos magni voluptatum id! Ea quos culpa eveniet! Sequi iure magnam velit, voluptatum molestiae sed, soluta perspiciatis eveniet aliquam repellat nam distinctio corrupti quidem eius eligendi amet harum tempora nesciunt cupiditate culpa odit neque inventore assumenda debitis! Minima voluptatibus autem vel omnis tempora exercitationem ex error dolor sequi, quaerat aliquid nihil sit debitis porro numquam. Quibusdam soluta repellendus nemo ipsam reiciendis quasi consectetur ab. Eius et nesciunt, dolores ullam ad, delectus nihil sapiente iure perspiciatis distinctio quibusdam repudiandae. Atque libero excepturi cumque, fugit cum facilis asperiores cupiditate iusto ratione reiciendis aliquam labore est mollitia velit corrupti perferendis exercitationem. Fugit, amet veritatis? Adipisci incidunt ab explicabo ut dolores dolorum deleniti recusandae, laboriosam iure pariatur possimus, animi libero vero, ea tenetur. Beatae porro labore rerum eligendi ea consequuntur voluptas voluptatem voluptate incidunt nostrum. Autem, quaerat quidem. Consectetur ipsum accusantium, ipsam neque ut expedita totam quisquam adipisci quia! Aliquam et modi soluta ad dolores? Optio doloribus unde eveniet obcaecati veritatis dicta possimus enim amet perspiciatis ratione repellendus reprehenderit, numquam voluptatibus labore, magnam iusto aperiam magni quos laudantium cumque?"
    },
]

export default () => {
    return (
        <div id="notices">
            <div className="noticeContainer">
                <h1>all notice</h1>
                {
                    notices.map((e, i) => {
                        return (
                            <div className="noticeItem" key={i}>
                                <div className="noticeHead">
                                    <span className="day">19</span>
                                    <span className="month">November</span>
                                </div>
                                <div className="noticeBody">
                                    <h3 className="noticeTitle">{e.title + " " + (parseInt(i) + 1)}</h3>
                                    <p className="notice-read-more">
                                        <Link to={`/notice/${e._id}`} style={{ cursor: "pointer" }}
                                        >Read More</Link>
                                    </p>
                                </div>
                            </div>
                        )
                    })
                }
            </div>
        </div>
    )
}

export const Notice = () => {
    const notice = notices.slice(notices.length - 5, notices.length);
    return (
        <>
            <div id="notices">
                <div className="noticeContainer">
                    <h1>Notice</h1>
                    {
                        notice.map((e, i) => {
                            return (
                                <div className="noticeItem" key={i}>
                                    <div className="noticeHead jcc">
                                        <span className="day">19</span>
                                        <span className="month">November</span>
                                    </div>
                                    <div className="noticeBody">
                                        <h3 className="noticeTitle mainnoticetitle">{e.title}</h3>
                                        <p className="notice-read-more">
                                            <Link to={`/notice/${e._id}`} style={{ cursor: "pointer" }}
                                            >Read More</Link>
                                        </p>
                                    </div>
                                </div>
                            )
                        })
                    }
                    <div className="allNotice">
                        <Link to="/notice">All Notice <i className="fa-solid fa-angles-right fa-beat-fade"></i></Link>
                    </div>
                </div>
            </div>
        </>
    )
}